const virDomainState = {
  VIR_DOMAIN_NOSTATE: 0,
  VIR_DOMAIN_RUNNING: 1,
  VIR_DOMAIN_BLOCKED: 2,
  VIR_DOMAIN_PAUSED: 3,
  VIR_DOMAIN_SHUTDOWN: 4,
  VIR_DOMAIN_SHUTOFF: 5,
  VIR_DOMAIN_CRASHED: 6,
  VIR_DOMAIN_PMSUSPENDED: 7
}

const virDomainNostateReason = {
  VIR_DOMAIN_NOSTATE_UNKNOWN: 0
}

const virDomainRunningReason = {
  VIR_DOMAIN_RUNNING_UNKNOWN: 0,
  VIR_DOMAIN_RUNNING_BOOTED: 1,
  VIR_DOMAIN_RUNNING_MIGRATED: 2,
  VIR_DOMAIN_RUNNING_RESTORED: 3,
  VIR_DOMAIN_RUNNING_FROM_SNAPSHOT: 4,
  VIR_DOMAIN_RUNNING_UNPAUSED: 5,
  VIR_DOMAIN_RUNNING_MIGRATION_CANCELED: 6,
  VIR_DOMAIN_RUNNING_SAVE_CANCELED: 7,
  VIR_DOMAIN_RUNNING_WAKEUP: 8,
  VIR_DOMAIN_RUNNING_CRASHED: 9,
  VIR_DOMAIN_RUNNING_POSTCOPY: 10
}

const virDomainBlockedReason = {
  VIR_DOMAIN_BLOCKED_UNKNOWN: 0
}

const virDomainPausedReason = {
  VIR_DOMAIN_PAUSED_UNKNOWN: 0,
  VIR_DOMAIN_PAUSED_USER: 1,
  VIR_DOMAIN_PAUSED_MIGRATION: 2,
  VIR_DOMAIN_PAUSED_SAVE: 3,
  VIR_DOMAIN_PAUSED_DUMP: 4,
  VIR_DOMAIN_PAUSED_IOERROR: 5,
  VIR_DOMAIN_PAUSED_WATCHDOG: 6,
  VIR_DOMAIN_PAUSED_FROM_SNAPSHOT: 7,
  VIR_DOMAIN_PAUSED_SHUTTING_DOWN: 8,
  VIR_DOMAIN_PAUSED_SNAPSHOT: 9,
  VIR_DOMAIN_PAUSED_CRASHED: 10,
  VIR_DOMAIN_PAUSED_STARTING_UP: 11,
  VIR_DOMAIN_PAUSED_POSTCOPY: 12,
  VIR_DOMAIN_PAUSED_POSTCOPY_FAILED: 13
}

const virDomainShutdownReason = {
  VIR_DOMAIN_SHUTDOWN_UNKNOWN: 0,
  VIR_DOMAIN_SHUTDOWN_USER: 1
}

const virDomainShutoffReason = {
  VIR_DOMAIN_SHUTOFF_UNKNOWN: 0,
  VIR_DOMAIN_SHUTOFF_SHUTDOWN: 1,
  VIR_DOMAIN_SHUTOFF_DESTROYED: 2,
  VIR_DOMAIN_SHUTOFF_CRASHED: 3,
  VIR_DOMAIN_SHUTOFF_MIGRATED: 4,
  VIR_DOMAIN_SHUTOFF_SAVED: 5,
  VIR_DOMAIN_SHUTOFF_FAILED: 6,
  VIR_DOMAIN_SHUTOFF_FROM_SNAPSHOT: 7,
  VIR_DOMAIN_SHUTOFF_DAEMON: 8
}

const virDomainCrashedReason = {
  VIR_DOMAIN_CRASHED_UNKNOWN: 0,
  VIR_DOMAIN_CRASHED_PANICKED: 1
}

const virDomainPMSuspendedReason = {
  VIR_DOMAIN_PMSUSPENDED_UNKNOWN: 0
}

const virDomainPMSuspendedDiskReason = {
  VIR_DOMAIN_PMSUSPENDED_DISK_UNKNOWN: 0
}

const virDomainControlState = {
  VIR_DOMAIN_CONTROL_OK: 0,
  VIR_DOMAIN_CONTROL_JOB: 1,
  VIR_DOMAIN_CONTROL_OCCUPIED: 2,
  VIR_DOMAIN_CONTROL_ERROR: 3
}

const virDomainControlErrorReason = {
  VIR_DOMAIN_CONTROL_ERROR_REASON_NONE: 0,
  VIR_DOMAIN_CONTROL_ERROR_REASON_UNKNOWN: 1,
  VIR_DOMAIN_CONTROL_ERROR_REASON_MONITOR: 2,
  VIR_DOMAIN_CONTROL_ERROR_REASON_INTERNAL: 3
}

const virDomainModificationImpact = {
  VIR_DOMAIN_AFFECT_CURRENT: 0,
  VIR_DOMAIN_AFFECT_LIVE: 1 << 0,
  VIR_DOMAIN_AFFECT_CONFIG: 1 << 1
}

const virDomainCreateFlags = {
  VIR_DOMAIN_NONE: 0,
  VIR_DOMAIN_START_PAUSED: 1 << 0,
  VIR_DOMAIN_START_AUTODESTROY: 1 << 1,
  VIR_DOMAIN_START_BYPASS_CACHE: 1 << 2,
  VIR_DOMAIN_START_FORCE_BOOT: 1 << 3,
  VIR_DOMAIN_START_VALIDATE: 1 << 4
}

const virDomainMemoryStatTags = {
  VIR_DOMAIN_MEMORY_STAT_SWAP_IN: 0,
  VIR_DOMAIN_MEMORY_STAT_SWAP_OUT: 1,
  VIR_DOMAIN_MEMORY_STAT_MAJOR_FAULT: 2,
  VIR_DOMAIN_MEMORY_STAT_MINOR_FAULT: 3,
  VIR_DOMAIN_MEMORY_STAT_UNUSED: 4,
  VIR_DOMAIN_MEMORY_STAT_AVAILABLE: 5,
  VIR_DOMAIN_MEMORY_STAT_ACTUAL_BALLOON: 6,
  VIR_DOMAIN_MEMORY_STAT_RSS: 7,
  VIR_DOMAIN_MEMORY_STAT_USABLE: 8,
  VIR_DOMAIN_MEMORY_STAT_LAST_UPDATE: 9,
  VIR_DOMAIN_MEMORY_STAT_DISK_CACHES: 10,
  VIR_DOMAIN_MEMORY_STAT_HUGETLB_PGALLOC: 11,
  VIR_DOMAIN_MEMORY_STAT_HUGETLB_PGFAIL: 12,
  VIR_DOMAIN_MEMORY_STAT_NR: 13
}

const virDomainCoreDumpFlags = {
  VIR_DUMP_CRASH: 1 << 0,
  VIR_DUMP_LIVE: 1 << 1,
  VIR_DUMP_BYPASS_CACHE: 1 << 2,
  VIR_DUMP_RESET: 1 << 3,
  VIR_DUMP_MEMORY_ONLY: 1 << 4
}

const virDomainCoreDumpFormat = {
  VIR_DOMAIN_CORE_DUMP_FORMAT_RAW: null,
  VIR_DOMAIN_CORE_DUMP_FORMAT_KDUMP_ZLIB: null,
  VIR_DOMAIN_CORE_DUMP_FORMAT_KDUMP_LZO: null,
  VIR_DOMAIN_CORE_DUMP_FORMAT_KDUMP_SNAPPY: null
}

const virDomainMigrateFlags = {
  VIR_MIGRATE_LIVE: 1 << 0,
  VIR_MIGRATE_PEER2PEER: 1 << 1,
  VIR_MIGRATE_TUNNELLED: 1 << 2,
  VIR_MIGRATE_PERSIST_DEST: 1 << 3,
  VIR_MIGRATE_UNDEFINE_SOURCE: 1 << 4,
  VIR_MIGRATE_PAUSED: 1 << 5,
  VIR_MIGRATE_NON_SHARED_DISK: 1 << 6,
  VIR_MIGRATE_NON_SHARED_INC: 1 << 7,
  VIR_MIGRATE_CHANGE_PROTECTION: 1 << 8,
  VIR_MIGRATE_UNSAFE: 1 << 9,
  VIR_MIGRATE_OFFLINE: 1 << 10,
  VIR_MIGRATE_COMPRESSED: 1 << 11,
  VIR_MIGRATE_ABORT_ON_ERROR: 1 << 12,
  VIR_MIGRATE_AUTO_CONVERGE: 1 << 13,
  VIR_MIGRATE_RDMA_PIN_ALL: 1 << 14,
  VIR_MIGRATE_POSTCOPY: 1 << 15,
  VIR_MIGRATE_TLS: 1 << 16,
  VIR_MIGRATE_PARALLEL: 1 << 17
}

const virDomainMigrateMaxSpeedFlags = {
  VIR_DOMAIN_MIGRATE_MAX_SPEED_POSTCOPY: 1 << 0
}

const virDomainShutdownFlagValues = {
  VIR_DOMAIN_SHUTDOWN_DEFAULT: 0,
  VIR_DOMAIN_SHUTDOWN_ACPI_POWER_BTN: 1 << 0,
  VIR_DOMAIN_SHUTDOWN_GUEST_AGENT: 1 << 1,
  VIR_DOMAIN_SHUTDOWN_INITCTL: 1 << 2,
  VIR_DOMAIN_SHUTDOWN_SIGNAL: 1 << 3,
  VIR_DOMAIN_SHUTDOWN_PARAVIRT: 1 << 4
}

const virDomainRebootFlagValues = {
  VIR_DOMAIN_REBOOT_DEFAULT: 0,
  VIR_DOMAIN_REBOOT_ACPI_POWER_BTN: 1 << 0,
  VIR_DOMAIN_REBOOT_GUEST_AGENT: 1 << 1,
  VIR_DOMAIN_REBOOT_INITCTL: 1 << 2,
  VIR_DOMAIN_REBOOT_SIGNAL: 1 << 3,
  VIR_DOMAIN_REBOOT_PARAVIRT: 1 << 4
}

const virDomainDestroyFlagsValues = {
  VIR_DOMAIN_DESTROY_DEFAULT: 0,
  VIR_DOMAIN_DESTROY_GRACEFUL: 1 << 0
}

const virDomainSaveRestoreFlags = {
  VIR_DOMAIN_SAVE_BYPASS_CACHE: 1 << 0,
  VIR_DOMAIN_SAVE_RUNNING: 1 << 1,
  VIR_DOMAIN_SAVE_PAUSED: 1 << 2
}

const virDomainMemoryModFlags = {
  VIR_DOMAIN_MEM_CURRENT: VIR_DOMAIN_AFFECT_CURRENT,
  VIR_DOMAIN_MEM_LIVE: VIR_DOMAIN_AFFECT_LIVE,
  VIR_DOMAIN_MEM_CONFIG: VIR_DOMAIN_AFFECT_CONFIG,
  VIR_DOMAIN_MEM_MAXIMUM: 1 << 2
}

const virDomainNumatuneMemMode = {
  VIR_DOMAIN_NUMATUNE_MEM_STRICT: 0,
  VIR_DOMAIN_NUMATUNE_MEM_PREFERRED: 1,
  VIR_DOMAIN_NUMATUNE_MEM_INTERLEAVE: 2
}

const virDomainMetadataType = {
  VIR_DOMAIN_METADATA_DESCRIPTION: 0,
  VIR_DOMAIN_METADATA_TITLE: 1,
  VIR_DOMAIN_METADATA_ELEMENT: 2
}

const virDomainXMLFlags = {
  VIR_DOMAIN_XML_SECURE: 1 << 0,
  VIR_DOMAIN_XML_INACTIVE: 1 << 1,
  VIR_DOMAIN_XML_UPDATE_CPU: 1 << 2,
  VIR_DOMAIN_XML_MIGRATABLE: 1 << 3
}

const virDomainSaveImageXMLFlags = {
  VIR_DOMAIN_SAVE_IMAGE_XML_SECURE: VIR_DOMAIN_XML_SECURE
}

const virDomainBlockResizeFlags = {
  VIR_DOMAIN_BLOCK_RESIZE_BYTES: 1 << 0
}

const virDomainMemoryFlags = {
  VIR_MEMORY_VIRTUAL: 1 << 0,
  VIR_MEMORY_PHYSICAL: 1 << 1
}

const virDomainDefineFlags = {
  VIR_DOMAIN_DEFINE_VALIDATE: 1 << 0
}

const virDomainUndefineFlagsValues = {
  VIR_DOMAIN_UNDEFINE_MANAGED_SAVE: 1 << 0,
  VIR_DOMAIN_UNDEFINE_SNAPSHOTS_METADATA: 1 << 1,
  VIR_DOMAIN_UNDEFINE_NVRAM: 1 << 2,
  VIR_DOMAIN_UNDEFINE_KEEP_NVRAM: 1 << 3,
  VIR_DOMAIN_UNDEFINE_CHECKPOINTS_METADATA: 1 << 4
}

const virConnectListAllDomainsFlags = {
  VIR_CONNECT_LIST_DOMAINS_ACTIVE: 1 << 0,
  VIR_CONNECT_LIST_DOMAINS_INACTIVE: 1 << 1,
  VIR_CONNECT_LIST_DOMAINS_PERSISTENT: 1 << 2,
  VIR_CONNECT_LIST_DOMAINS_TRANSIENT: 1 << 3,
  VIR_CONNECT_LIST_DOMAINS_RUNNING: 1 << 4,
  VIR_CONNECT_LIST_DOMAINS_PAUSED: 1 << 5,
  VIR_CONNECT_LIST_DOMAINS_SHUTOFF: 1 << 6,
  VIR_CONNECT_LIST_DOMAINS_OTHER: 1 << 7,
  VIR_CONNECT_LIST_DOMAINS_MANAGEDSAVE: 1 << 8,
  VIR_CONNECT_LIST_DOMAINS_NO_MANAGEDSAVE: 1 << 9,
  VIR_CONNECT_LIST_DOMAINS_AUTOSTART: 1 << 10,
  VIR_CONNECT_LIST_DOMAINS_NO_AUTOSTART: 1 << 11,
  VIR_CONNECT_LIST_DOMAINS_HAS_SNAPSHOT: 1 << 12,
  VIR_CONNECT_LIST_DOMAINS_NO_SNAPSHOT: 1 << 13,
  VIR_CONNECT_LIST_DOMAINS_HAS_CHECKPOINT: 1 << 14,
  VIR_CONNECT_LIST_DOMAINS_NO_CHECKPOINT: 1 << 15
}

const virVcpuState = {
  VIR_VCPU_OFFLINE: 0,
  VIR_VCPU_RUNNING: 1,
  VIR_VCPU_BLOCKED: 2
}

const virDomainVcpuFlags = {
  VIR_DOMAIN_VCPU_CURRENT: VIR_DOMAIN_AFFECT_CURRENT,
  VIR_DOMAIN_VCPU_LIVE: VIR_DOMAIN_AFFECT_LIVE,
  VIR_DOMAIN_VCPU_CONFIG: VIR_DOMAIN_AFFECT_CONFIG,
  VIR_DOMAIN_VCPU_MAXIMUM: 1 << 2,
  VIR_DOMAIN_VCPU_GUEST: 1 << 3,
  VIR_DOMAIN_VCPU_HOTPLUGGABLE: 1 << 4
}

const virDomainDeviceModifyFlags = {
  VIR_DOMAIN_DEVICE_MODIFY_CURRENT: VIR_DOMAIN_AFFECT_CURRENT,
  VIR_DOMAIN_DEVICE_MODIFY_LIVE: VIR_DOMAIN_AFFECT_LIVE,
  VIR_DOMAIN_DEVICE_MODIFY_CONFIG: VIR_DOMAIN_AFFECT_CONFIG,
  VIR_DOMAIN_DEVICE_MODIFY_FORCE: 1 << 2
}

const virDomainStatsTypes = {
  VIR_DOMAIN_STATS_STATE: 1 << 0,
  VIR_DOMAIN_STATS_CPU_TOTAL: 1 << 1,
  VIR_DOMAIN_STATS_BALLOON: 1 << 2,
  VIR_DOMAIN_STATS_VCPU: 1 << 3,
  VIR_DOMAIN_STATS_INTERFACE: 1 << 4,
  VIR_DOMAIN_STATS_BLOCK: 1 << 5,
  VIR_DOMAIN_STATS_PERF: 1 << 6,
  VIR_DOMAIN_STATS_IOTHREAD: 1 << 7
}

const virConnectGetAllDomainStatsFlags = {
  VIR_CONNECT_GET_ALL_DOMAINS_STATS_ACTIVE: VIR_CONNECT_LIST_DOMAINS_ACTIVE,
  VIR_CONNECT_GET_ALL_DOMAINS_STATS_INACTIVE: VIR_CONNECT_LIST_DOMAINS_INACTIVE,
  VIR_CONNECT_GET_ALL_DOMAINS_STATS_PERSISTENT: VIR_CONNECT_LIST_DOMAINS_PERSISTENT,
  VIR_CONNECT_GET_ALL_DOMAINS_STATS_TRANSIENT: VIR_CONNECT_LIST_DOMAINS_TRANSIENT,
  VIR_CONNECT_GET_ALL_DOMAINS_STATS_RUNNING: VIR_CONNECT_LIST_DOMAINS_RUNNING,
  VIR_CONNECT_GET_ALL_DOMAINS_STATS_PAUSED: VIR_CONNECT_LIST_DOMAINS_PAUSED,
  VIR_CONNECT_GET_ALL_DOMAINS_STATS_SHUTOFF: VIR_CONNECT_LIST_DOMAINS_SHUTOFF,
  VIR_CONNECT_GET_ALL_DOMAINS_STATS_OTHER: VIR_CONNECT_LIST_DOMAINS_OTHER,
  VIR_CONNECT_GET_ALL_DOMAINS_STATS_NOWAIT: 1 << 29,
  VIR_CONNECT_GET_ALL_DOMAINS_STATS_BACKING: 1 << 30,
  VIR_CONNECT_GET_ALL_DOMAINS_STATS_ENFORCE_STATS: NaN << 31
}

const virDomainBlockJobType = {
  VIR_DOMAIN_BLOCK_JOB_TYPE_UNKNOWN: 0,
  VIR_DOMAIN_BLOCK_JOB_TYPE_PULL: 1,
  VIR_DOMAIN_BLOCK_JOB_TYPE_COPY: 2,
  VIR_DOMAIN_BLOCK_JOB_TYPE_COMMIT: 3,
  VIR_DOMAIN_BLOCK_JOB_TYPE_ACTIVE_COMMIT: 4,
  VIR_DOMAIN_BLOCK_JOB_TYPE_BACKUP: 5
}

const virDomainBlockJobAbortFlags = {
  VIR_DOMAIN_BLOCK_JOB_ABORT_ASYNC: 1 << 0,
  VIR_DOMAIN_BLOCK_JOB_ABORT_PIVOT: 1 << 1
}

const virDomainBlockJobInfoFlags = {
  VIR_DOMAIN_BLOCK_JOB_INFO_BANDWIDTH_BYTES: 1 << 0
}

const virDomainBlockJobSetSpeedFlags = {
  VIR_DOMAIN_BLOCK_JOB_SPEED_BANDWIDTH_BYTES: 1 << 0
}

const virDomainBlockPullFlags = {
  VIR_DOMAIN_BLOCK_PULL_BANDWIDTH_BYTES: 1 << 6
}

const virDomainBlockRebaseFlags = {
  VIR_DOMAIN_BLOCK_REBASE_SHALLOW: 1 << 0,
  VIR_DOMAIN_BLOCK_REBASE_REUSE_EXT: 1 << 1,
  VIR_DOMAIN_BLOCK_REBASE_COPY_RAW: 1 << 2,
  VIR_DOMAIN_BLOCK_REBASE_COPY: 1 << 3,
  VIR_DOMAIN_BLOCK_REBASE_RELATIVE: 1 << 4,
  VIR_DOMAIN_BLOCK_REBASE_COPY_DEV: 1 << 5,
  VIR_DOMAIN_BLOCK_REBASE_BANDWIDTH_BYTES: 1 << 6
}

const virDomainBlockCopyFlags = {
  VIR_DOMAIN_BLOCK_COPY_SHALLOW: 1 << 0,
  VIR_DOMAIN_BLOCK_COPY_REUSE_EXT: 1 << 1,
  VIR_DOMAIN_BLOCK_COPY_TRANSIENT_JOB: 1 << 2
}

const virDomainBlockCommitFlags = {
  VIR_DOMAIN_BLOCK_COMMIT_SHALLOW: 1 << 0,
  VIR_DOMAIN_BLOCK_COMMIT_DELETE: 1 << 1,
  VIR_DOMAIN_BLOCK_COMMIT_ACTIVE: 1 << 2,
  VIR_DOMAIN_BLOCK_COMMIT_RELATIVE: 1 << 3,
  VIR_DOMAIN_BLOCK_COMMIT_BANDWIDTH_BYTES: 1 << 4
}

const virDomainDiskErrorCode = {
  VIR_DOMAIN_DISK_ERROR_NONE: 0,
  VIR_DOMAIN_DISK_ERROR_UNSPEC: 1,
  VIR_DOMAIN_DISK_ERROR_NO_SPACE: 2
}

const virKeycodeSet = {
  VIR_KEYCODE_SET_LINUX: 0,
  VIR_KEYCODE_SET_XT: 1,
  VIR_KEYCODE_SET_ATSET1: 2,
  VIR_KEYCODE_SET_ATSET2: 3,
  VIR_KEYCODE_SET_ATSET3: 4,
  VIR_KEYCODE_SET_OSX: 5,
  VIR_KEYCODE_SET_XT_KBD: 6,
  VIR_KEYCODE_SET_USB: 7,
  VIR_KEYCODE_SET_WIN32: 8,
  VIR_KEYCODE_SET_QNUM: 9
}

const virDomainProcessSignal = {
  VIR_DOMAIN_PROCESS_SIGNAL_NOP: 0,
  VIR_DOMAIN_PROCESS_SIGNAL_HUP: 1,
  VIR_DOMAIN_PROCESS_SIGNAL_INT: 2,
  VIR_DOMAIN_PROCESS_SIGNAL_QUIT: 3,
  VIR_DOMAIN_PROCESS_SIGNAL_ILL: 4,
  VIR_DOMAIN_PROCESS_SIGNAL_TRAP: 5,
  VIR_DOMAIN_PROCESS_SIGNAL_ABRT: 6,
  VIR_DOMAIN_PROCESS_SIGNAL_BUS: 7,
  VIR_DOMAIN_PROCESS_SIGNAL_FPE: 8,
  VIR_DOMAIN_PROCESS_SIGNAL_KILL: 9,
  VIR_DOMAIN_PROCESS_SIGNAL_USR1: 10,
  VIR_DOMAIN_PROCESS_SIGNAL_SEGV: 11,
  VIR_DOMAIN_PROCESS_SIGNAL_USR2: 12,
  VIR_DOMAIN_PROCESS_SIGNAL_PIPE: 13,
  VIR_DOMAIN_PROCESS_SIGNAL_ALRM: 14,
  VIR_DOMAIN_PROCESS_SIGNAL_TERM: 15,
  VIR_DOMAIN_PROCESS_SIGNAL_STKFLT: 16,
  VIR_DOMAIN_PROCESS_SIGNAL_CHLD: 17,
  VIR_DOMAIN_PROCESS_SIGNAL_CONT: 18,
  VIR_DOMAIN_PROCESS_SIGNAL_STOP: 19,
  VIR_DOMAIN_PROCESS_SIGNAL_TSTP: 20,
  VIR_DOMAIN_PROCESS_SIGNAL_TTIN: 21,
  VIR_DOMAIN_PROCESS_SIGNAL_TTOU: 22,
  VIR_DOMAIN_PROCESS_SIGNAL_URG: 23,
  VIR_DOMAIN_PROCESS_SIGNAL_XCPU: 24,
  VIR_DOMAIN_PROCESS_SIGNAL_XFSZ: 25,
  VIR_DOMAIN_PROCESS_SIGNAL_VTALRM: 26,
  VIR_DOMAIN_PROCESS_SIGNAL_PROF: 27,
  VIR_DOMAIN_PROCESS_SIGNAL_WINCH: 28,
  VIR_DOMAIN_PROCESS_SIGNAL_POLL: 29,
  VIR_DOMAIN_PROCESS_SIGNAL_PWR: 30,
  VIR_DOMAIN_PROCESS_SIGNAL_SYS: 31,
  VIR_DOMAIN_PROCESS_SIGNAL_RT0: 32,
  VIR_DOMAIN_PROCESS_SIGNAL_RT1: 33,
  VIR_DOMAIN_PROCESS_SIGNAL_RT2: 34,
  VIR_DOMAIN_PROCESS_SIGNAL_RT3: 35,
  VIR_DOMAIN_PROCESS_SIGNAL_RT4: 36,
  VIR_DOMAIN_PROCESS_SIGNAL_RT5: 37,
  VIR_DOMAIN_PROCESS_SIGNAL_RT6: 38,
  VIR_DOMAIN_PROCESS_SIGNAL_RT7: 39,
  VIR_DOMAIN_PROCESS_SIGNAL_RT8: 40,
  VIR_DOMAIN_PROCESS_SIGNAL_RT9: 41,
  VIR_DOMAIN_PROCESS_SIGNAL_RT10: 42,
  VIR_DOMAIN_PROCESS_SIGNAL_RT11: 43,
  VIR_DOMAIN_PROCESS_SIGNAL_RT12: 44,
  VIR_DOMAIN_PROCESS_SIGNAL_RT13: 45,
  VIR_DOMAIN_PROCESS_SIGNAL_RT14: 46,
  VIR_DOMAIN_PROCESS_SIGNAL_RT15: 47,
  VIR_DOMAIN_PROCESS_SIGNAL_RT16: 48,
  VIR_DOMAIN_PROCESS_SIGNAL_RT17: 49,
  VIR_DOMAIN_PROCESS_SIGNAL_RT18: 50,
  VIR_DOMAIN_PROCESS_SIGNAL_RT19: 51,
  VIR_DOMAIN_PROCESS_SIGNAL_RT20: 52,
  VIR_DOMAIN_PROCESS_SIGNAL_RT21: 53,
  VIR_DOMAIN_PROCESS_SIGNAL_RT22: 54,
  VIR_DOMAIN_PROCESS_SIGNAL_RT23: 55,
  VIR_DOMAIN_PROCESS_SIGNAL_RT24: 56,
  VIR_DOMAIN_PROCESS_SIGNAL_RT25: 57,
  VIR_DOMAIN_PROCESS_SIGNAL_RT26: 58,
  VIR_DOMAIN_PROCESS_SIGNAL_RT27: 59,
  VIR_DOMAIN_PROCESS_SIGNAL_RT28: 60,
  VIR_DOMAIN_PROCESS_SIGNAL_RT29: 61,
  VIR_DOMAIN_PROCESS_SIGNAL_RT30: 62,
  VIR_DOMAIN_PROCESS_SIGNAL_RT31: 63,
  VIR_DOMAIN_PROCESS_SIGNAL_RT32: 64
}

const virDomainEventType = {
  VIR_DOMAIN_EVENT_DEFINED: 0,
  VIR_DOMAIN_EVENT_UNDEFINED: 1,
  VIR_DOMAIN_EVENT_STARTED: 2,
  VIR_DOMAIN_EVENT_SUSPENDED: 3,
  VIR_DOMAIN_EVENT_RESUMED: 4,
  VIR_DOMAIN_EVENT_STOPPED: 5,
  VIR_DOMAIN_EVENT_SHUTDOWN: 6,
  VIR_DOMAIN_EVENT_PMSUSPENDED: 7,
  VIR_DOMAIN_EVENT_CRASHED: 8
}

const virDomainEventDefinedDetailType = {
  VIR_DOMAIN_EVENT_DEFINED_ADDED: 0,
  VIR_DOMAIN_EVENT_DEFINED_UPDATED: 1,
  VIR_DOMAIN_EVENT_DEFINED_RENAMED: 2,
  VIR_DOMAIN_EVENT_DEFINED_FROM_SNAPSHOT: 3
}

const virDomainEventUndefinedDetailType = {
  VIR_DOMAIN_EVENT_UNDEFINED_REMOVED: 0,
  VIR_DOMAIN_EVENT_UNDEFINED_RENAMED: 1
}

const virDomainEventStartedDetailType = {
  VIR_DOMAIN_EVENT_STARTED_BOOTED: 0,
  VIR_DOMAIN_EVENT_STARTED_MIGRATED: 1,
  VIR_DOMAIN_EVENT_STARTED_RESTORED: 2,
  VIR_DOMAIN_EVENT_STARTED_FROM_SNAPSHOT: 3,
  VIR_DOMAIN_EVENT_STARTED_WAKEUP: 4
}

const virDomainEventSuspendedDetailType = {
  VIR_DOMAIN_EVENT_SUSPENDED_PAUSED: 0,
  VIR_DOMAIN_EVENT_SUSPENDED_MIGRATED: 1,
  VIR_DOMAIN_EVENT_SUSPENDED_IOERROR: 2,
  VIR_DOMAIN_EVENT_SUSPENDED_WATCHDOG: 3,
  VIR_DOMAIN_EVENT_SUSPENDED_RESTORED: 4,
  VIR_DOMAIN_EVENT_SUSPENDED_FROM_SNAPSHOT: 5,
  VIR_DOMAIN_EVENT_SUSPENDED_API_ERROR: 6,
  VIR_DOMAIN_EVENT_SUSPENDED_POSTCOPY: 7,
  VIR_DOMAIN_EVENT_SUSPENDED_POSTCOPY_FAILED: 8
}

const virDomainEventResumedDetailType = {
  VIR_DOMAIN_EVENT_RESUMED_UNPAUSED: 0,
  VIR_DOMAIN_EVENT_RESUMED_MIGRATED: 1,
  VIR_DOMAIN_EVENT_RESUMED_FROM_SNAPSHOT: 2,
  VIR_DOMAIN_EVENT_RESUMED_POSTCOPY: 3
}

const virDomainEventStoppedDetailType = {
  VIR_DOMAIN_EVENT_STOPPED_SHUTDOWN: 0,
  VIR_DOMAIN_EVENT_STOPPED_DESTROYED: 1,
  VIR_DOMAIN_EVENT_STOPPED_CRASHED: 2,
  VIR_DOMAIN_EVENT_STOPPED_MIGRATED: 3,
  VIR_DOMAIN_EVENT_STOPPED_SAVED: 4,
  VIR_DOMAIN_EVENT_STOPPED_FAILED: 5,
  VIR_DOMAIN_EVENT_STOPPED_FROM_SNAPSHOT: 6
}

const virDomainEventShutdownDetailType = {
  VIR_DOMAIN_EVENT_SHUTDOWN_FINISHED: 0,
  VIR_DOMAIN_EVENT_SHUTDOWN_GUEST: 1,
  VIR_DOMAIN_EVENT_SHUTDOWN_HOST: 2
}

const virDomainEventPMSuspendedDetailType = {
  VIR_DOMAIN_EVENT_PMSUSPENDED_MEMORY: 0,
  VIR_DOMAIN_EVENT_PMSUSPENDED_DISK: 1
}

const virDomainEventCrashedDetailType = {
  VIR_DOMAIN_EVENT_CRASHED_PANICKED: 0
}

const virDomainJobType = {
  VIR_DOMAIN_JOB_NONE: 0,
  VIR_DOMAIN_JOB_BOUNDED: 1,
  VIR_DOMAIN_JOB_UNBOUNDED: 2,
  VIR_DOMAIN_JOB_COMPLETED: 3,
  VIR_DOMAIN_JOB_FAILED: 4,
  VIR_DOMAIN_JOB_CANCELLED: 5
}

const virDomainGetJobStatsFlags = {
  VIR_DOMAIN_JOB_STATS_COMPLETED: 1 << 0,
  VIR_DOMAIN_JOB_STATS_KEEP_COMPLETED: 1 << 1
}

const virDomainJobOperation = {
  VIR_DOMAIN_JOB_OPERATION_UNKNOWN: 0,
  VIR_DOMAIN_JOB_OPERATION_START: 1,
  VIR_DOMAIN_JOB_OPERATION_SAVE: 2,
  VIR_DOMAIN_JOB_OPERATION_RESTORE: 3,
  VIR_DOMAIN_JOB_OPERATION_MIGRATION_IN: 4,
  VIR_DOMAIN_JOB_OPERATION_MIGRATION_OUT: 5,
  VIR_DOMAIN_JOB_OPERATION_SNAPSHOT: 6,
  VIR_DOMAIN_JOB_OPERATION_SNAPSHOT_REVERT: 7,
  VIR_DOMAIN_JOB_OPERATION_DUMP: 8,
  VIR_DOMAIN_JOB_OPERATION_BACKUP: 9
}

const virDomainEventWatchdogAction = {
  VIR_DOMAIN_EVENT_WATCHDOG_NONE: 0,
  VIR_DOMAIN_EVENT_WATCHDOG_PAUSE: null,
  VIR_DOMAIN_EVENT_WATCHDOG_RESET: null,
  VIR_DOMAIN_EVENT_WATCHDOG_POWEROFF: null,
  VIR_DOMAIN_EVENT_WATCHDOG_SHUTDOWN: null,
  VIR_DOMAIN_EVENT_WATCHDOG_DEBUG: null,
  VIR_DOMAIN_EVENT_WATCHDOG_INJECTNMI: null
}

const virDomainEventIOErrorAction = {
  VIR_DOMAIN_EVENT_IO_ERROR_NONE: 0,
  VIR_DOMAIN_EVENT_IO_ERROR_PAUSE: null,
  VIR_DOMAIN_EVENT_IO_ERROR_REPORT: null
}

const virDomainEventGraphicsPhase = {
  VIR_DOMAIN_EVENT_GRAPHICS_CONNECT: 0,
  VIR_DOMAIN_EVENT_GRAPHICS_INITIALIZE: null,
  VIR_DOMAIN_EVENT_GRAPHICS_DISCONNECT: null
}

const virDomainEventGraphicsAddressType = {
  VIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_IPV4: null,
  VIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_IPV6: null,
  VIR_DOMAIN_EVENT_GRAPHICS_ADDRESS_UNIX: null
}

const virConnectDomainEventBlockJobStatus = {
  VIR_DOMAIN_BLOCK_JOB_COMPLETED: 0,
  VIR_DOMAIN_BLOCK_JOB_FAILED: 1,
  VIR_DOMAIN_BLOCK_JOB_CANCELED: 2,
  VIR_DOMAIN_BLOCK_JOB_READY: 3
}

const virConnectDomainEventDiskChangeReason = {
  VIR_DOMAIN_EVENT_DISK_CHANGE_MISSING_ON_START: 0,
  VIR_DOMAIN_EVENT_DISK_DROP_MISSING_ON_START: 1
}

const virDomainEventTrayChangeReason = {
  VIR_DOMAIN_EVENT_TRAY_CHANGE_OPEN: 0,
  VIR_DOMAIN_EVENT_TRAY_CHANGE_CLOSE: null
}

const virConnectDomainEventAgentLifecycleState = {
  VIR_CONNECT_DOMAIN_EVENT_AGENT_LIFECYCLE_STATE_CONNECTED: 1,
  VIR_CONNECT_DOMAIN_EVENT_AGENT_LIFECYCLE_STATE_DISCONNECTED: 2
}

const virConnectDomainEventAgentLifecycleReason = {
  VIR_CONNECT_DOMAIN_EVENT_AGENT_LIFECYCLE_REASON_UNKNOWN: 0,
  VIR_CONNECT_DOMAIN_EVENT_AGENT_LIFECYCLE_REASON_DOMAIN_STARTED: 1,
  VIR_CONNECT_DOMAIN_EVENT_AGENT_LIFECYCLE_REASON_CHANNEL: 2
}

const virDomainEventID = {
  VIR_DOMAIN_EVENT_ID_LIFECYCLE: 0,
  VIR_DOMAIN_EVENT_ID_REBOOT: 1,
  VIR_DOMAIN_EVENT_ID_RTC_CHANGE: 2,
  VIR_DOMAIN_EVENT_ID_WATCHDOG: 3,
  VIR_DOMAIN_EVENT_ID_IO_ERROR: 4,
  VIR_DOMAIN_EVENT_ID_GRAPHICS: 5,
  VIR_DOMAIN_EVENT_ID_IO_ERROR_REASON: 6,
  VIR_DOMAIN_EVENT_ID_CONTROL_ERROR: 7,
  VIR_DOMAIN_EVENT_ID_BLOCK_JOB: 8,
  VIR_DOMAIN_EVENT_ID_DISK_CHANGE: 9,
  VIR_DOMAIN_EVENT_ID_TRAY_CHANGE: 10,
  VIR_DOMAIN_EVENT_ID_PMWAKEUP: 11,
  VIR_DOMAIN_EVENT_ID_PMSUSPEND: 12,
  VIR_DOMAIN_EVENT_ID_BALLOON_CHANGE: 13,
  VIR_DOMAIN_EVENT_ID_PMSUSPEND_DISK: 14,
  VIR_DOMAIN_EVENT_ID_DEVICE_REMOVED: 15,
  VIR_DOMAIN_EVENT_ID_BLOCK_JOB_2: 16,
  VIR_DOMAIN_EVENT_ID_TUNABLE: 17,
  VIR_DOMAIN_EVENT_ID_AGENT_LIFECYCLE: 18,
  VIR_DOMAIN_EVENT_ID_DEVICE_ADDED: 19,
  VIR_DOMAIN_EVENT_ID_MIGRATION_ITERATION: 20,
  VIR_DOMAIN_EVENT_ID_JOB_COMPLETED: 21,
  VIR_DOMAIN_EVENT_ID_DEVICE_REMOVAL_FAILED: 22,
  VIR_DOMAIN_EVENT_ID_METADATA_CHANGE: 23,
  VIR_DOMAIN_EVENT_ID_BLOCK_THRESHOLD: 24
}

const virDomainConsoleFlags = {
  VIR_DOMAIN_CONSOLE_FORCE: 1 << 0,
  VIR_DOMAIN_CONSOLE_SAFE: 1 << 1
}

const virDomainChannelFlags = {
  VIR_DOMAIN_CHANNEL_FORCE: 1 << 0
}

const virDomainOpenGraphicsFlags = {
  VIR_DOMAIN_OPEN_GRAPHICS_SKIPAUTH: 1 << 0
}

const virDomainSetTimeFlags = {
  VIR_DOMAIN_TIME_SYNC: 1 << 0
}

const virSchedParameterType = {
  VIR_DOMAIN_SCHED_FIELD_INT: VIR_TYPED_PARAM_INT,
  VIR_DOMAIN_SCHED_FIELD_UINT: VIR_TYPED_PARAM_UINT,
  VIR_DOMAIN_SCHED_FIELD_LLONG: VIR_TYPED_PARAM_LLONG,
  VIR_DOMAIN_SCHED_FIELD_ULLONG: VIR_TYPED_PARAM_ULLONG,
  VIR_DOMAIN_SCHED_FIELD_DOUBLE: VIR_TYPED_PARAM_DOUBLE,
  VIR_DOMAIN_SCHED_FIELD_BOOLEAN: VIR_TYPED_PARAM_BOOLEAN
}

const virBlkioParameterType = {
  VIR_DOMAIN_BLKIO_PARAM_INT: VIR_TYPED_PARAM_INT,
  VIR_DOMAIN_BLKIO_PARAM_UINT: VIR_TYPED_PARAM_UINT,
  VIR_DOMAIN_BLKIO_PARAM_LLONG: VIR_TYPED_PARAM_LLONG,
  VIR_DOMAIN_BLKIO_PARAM_ULLONG: VIR_TYPED_PARAM_ULLONG,
  VIR_DOMAIN_BLKIO_PARAM_DOUBLE: VIR_TYPED_PARAM_DOUBLE,
  VIR_DOMAIN_BLKIO_PARAM_BOOLEAN: VIR_TYPED_PARAM_BOOLEAN
}

const virMemoryParameterType = {
  VIR_DOMAIN_MEMORY_PARAM_INT: VIR_TYPED_PARAM_INT,
  VIR_DOMAIN_MEMORY_PARAM_UINT: VIR_TYPED_PARAM_UINT,
  VIR_DOMAIN_MEMORY_PARAM_LLONG: VIR_TYPED_PARAM_LLONG,
  VIR_DOMAIN_MEMORY_PARAM_ULLONG: VIR_TYPED_PARAM_ULLONG,
  VIR_DOMAIN_MEMORY_PARAM_DOUBLE: VIR_TYPED_PARAM_DOUBLE,
  VIR_DOMAIN_MEMORY_PARAM_BOOLEAN: VIR_TYPED_PARAM_BOOLEAN
}

const virDomainInterfaceAddressesSource = {
  VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE: 0,
  VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_AGENT: 1,
  VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_ARP: 2
}

const virDomainSetUserPasswordFlags = {
  VIR_DOMAIN_PASSWORD_ENCRYPTED: 1 << 0
}

const virDomainLifecycle = {
  VIR_DOMAIN_LIFECYCLE_POWEROFF: 0,
  VIR_DOMAIN_LIFECYCLE_REBOOT: 1,
  VIR_DOMAIN_LIFECYCLE_CRASH: 2
}

const virDomainLifecycleAction = {
  VIR_DOMAIN_LIFECYCLE_ACTION_DESTROY: 0,
  VIR_DOMAIN_LIFECYCLE_ACTION_RESTART: 1,
  VIR_DOMAIN_LIFECYCLE_ACTION_RESTART_RENAME: 2,
  VIR_DOMAIN_LIFECYCLE_ACTION_PRESERVE: 3,
  VIR_DOMAIN_LIFECYCLE_ACTION_COREDUMP_DESTROY: 4,
  VIR_DOMAIN_LIFECYCLE_ACTION_COREDUMP_RESTART: 5
}

const virDomainGuestInfoTypes = {
  VIR_DOMAIN_GUEST_INFO_USERS: 1 << 0,
  VIR_DOMAIN_GUEST_INFO_OS: 1 << 1,
  VIR_DOMAIN_GUEST_INFO_TIMEZONE: 1 << 2,
  VIR_DOMAIN_GUEST_INFO_HOSTNAME: 1 << 3,
  VIR_DOMAIN_GUEST_INFO_FILESYSTEM: 1 << 4
}

const virDomainAgentResponseTimeoutValues = {
  VIR_DOMAIN_AGENT_RESPONSE_TIMEOUT_BLOCK: -2,
  VIR_DOMAIN_AGENT_RESPONSE_TIMEOUT_DEFAULT: -1,
  VIR_DOMAIN_AGENT_RESPONSE_TIMEOUT_NOWAIT: 0
}

const virDomainBackupBeginFlags = {
  VIR_DOMAIN_BACKUP_BEGIN_REUSE_EXTERNAL: 1 << 0
}
